import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans"; // import font
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // add font to className, also add antialiased and dark mode
    <html lang="en" className={`${GeistSans.className} antialiased dark:bg-gray-950 `}>
      <body>
        <Theme>
          {children}
        </Theme>
        </body>
    </html>
  );
}